### ISSUE TITLE
No information on date of events for given patient

### ISSUE THREAD

**Issue by pdulak** [dtandev/coronavirus#1]
There is no information on the event dates on the particular patient. I see that the event date in the data file is taken from the official communication about infection, death or recovery. The problem is that there is no possibility to check for the particular patient when he was infected and when he died or recovered. 

Is this possible given the data sources you have?

**Comment by pdulak** [comment]
This page can be helpful too: 

https://www.gov.pl/web/koronawirus/wykaz-zarazen-koronawirusem-sars-cov-2

**Comment by dtandev** [comment]
If I good understand you would like to have possibilities calculate the time between infection confirmation and death or recovery for a particular patient?

> Is this possible given the data sources you have?
Today, yes. In the next week? I don't think so. Currently, we have much more detailed information because there are not too many confirmed cases. When in a single day we will have 200-300 infections, nobody will inform about gender, age or history of travel. It is impossible. Now we have lots of empty cells in the table, because of no additional information. I would like to avoid collect specific data which will be useless because only a few rows contain a value. I am happy if the Health Ministry informs us about cities (not only provinces), but it doesn't always happen. Today we had problems because in the communique was information about 9 of confirmations in Dolnośląskie (Wrocław, Wałbrzych) without detail information how much people were diagnosed in Wałbrzych and in Wroclaw. 

Paraphrasing: "one infection is a tragedy a million is a statistic". 
I am afraid every patient will be only a part of the statistic in the next week. Unfortunately...

**Comment by pdulak** [comment]
I afraid that you are right, there will be no possibility to gather such information when there will be more patients. 

I'm curious if the authorities are gathering such information in any way... Each hospital has such info, but it would be great to have it somewhere - available for public use...

As per now, I will close this issue since there is nothing more we can do about it now...
